### ISSUE TITLE
🚀 🟨  Data U + Kiara collabo event in Phnom Penh in Jan 2024 

### ISSUE THREAD

**Issue by daijapan** [daijapan/Kiara-University#7]
5W1H:
Why: Try some collaboration with local company - DataU.org 
What : Data Hackathon - Download Kaggle.com data and try to make value out of it
Who  : Sok, Dave, Rizwan 

Data U event on 13 Jan (Sat) 

——

Venue :

——

(Today’s step 1-2-3)

13:00-13:30 - open the room and we welcome the participants 
13:30- 13:50
0 : warm intro - hey we are Rizwan and Dave  - call us R&D!! You do warm intro too.
13:50-14:10
1: Get to know how to use kaggle! Welcome to open data science. Download CSV + do analysis + try to make some value with your deep insight. 
14:10 - 15:00
2: today we have prepared some light weight data (should be less than 1MB = easy to analyze) You can group up the team of 4-5 ppl - for finance (=make money!) , medical (=save life!)  , NASA (= discover the mystery of universe!)
15:00- 15:10 break
15:10 - 15:30
3: Continue the work! Don’t sleep. Everyone should help each other.
15:30-15:50
4 : Each team do 5min pitch about good / bad / possible next step out of your data-hackathon
15:50-16:00
5: Closing 

——
The data we prepared 
Source - you can use google translate to read this page
https://qiita.com/daisuke-team-ai/items/f8e3275f1d3ca7e9bfcd

——

(Finance data)

Bitcoin Price Prediction (LightWeight CSV)
https://www.kaggle.com/team-ai/bitcoin-price-prediction

Foreign Exchange (FX) Prediction - USD/JPY https://www.kaggle.com/team-ai/foreign-exchange-fx-prediction-usdjpy

Foreign Exchange(FX) Prediction - EUR/USD https://www.kaggle.com/meehau/EURUSD/kernels

StockPrice and News ニュースと株価の相関分析(6MB) https://www.kaggle.com/aaron7sun/stocknews
Loan Data for risk analysis 貸付リスク計算データ (6KB 軽め) https://www.kaggle.com/zhijinzhai/loandata

Below are free to use - you can check nintendo, apple stock price for free 

Yahoo finance
https://finance.yahoo.com/

Google finance 
https://support.google.com/docs/answer/3093281?hl=en

(Medical data ) 

Synchronized brainwave dataset 脳波 https://www.kaggle.com/berkeley-biosense/synchronized-brainwave-dataset
Breast Cancer Wisconsin (Diagnostic) Data Set 乳がん https://www.kaggle.com/uciml/breast-cancer-wisconsin-data
Hospital General Information 病院 https://www.kaggle.com/cms/hospital-general-information
Zika Virus Epidemic ジカ熱 https://www.kaggle.com/cdc/zika-virus-epidemic
Cervical Cancer Risk Classification 子宮頸がん https://www.kaggle.com/loveall/cervical-cancer-risk-classification
Medical Appointment No Shows 患者のドタキャン分析 https://www.kaggle.com/joniarroba/noshowappointments
Mental Health in Tech Survey テック業界のメンタルヘルス https://www.kaggle.com/osmi/mental-health-in-tech-survey

(Space data ) 

Exoplanet Hunting in Deep Space 惑星探査データ https://www.kaggle.com/keplersmachines/kepler-labelled-time-series-data
Solar Radiation Prediction 太陽の放射線データ https://www.kaggle.com/dronio/SolarEnergy
Climate Change: Earth Surface Temperature Data 地球の表面温度データ https://www.kaggle.com/berkeleyearth/climate-change-earth-surface-temperature-data
Meteorite Landings 隕石の衝突データ https://www.kaggle.com/nasa/meteorite-landings
UFO Sightings UFO発見データ https://www.kaggle.com/NUFORC/ufo-sightings
Open Exoplanet Catalogue 太陽系外惑星データ https://www.kaggle.com/mrisdal/open-exoplanet-catalogue
Kepler Exoplanet Search Results 太陽系外惑星データ2 https://www.kaggle.com/nasa/kepler-exoplanet-search-results/kernels
NASAの太陽系外惑星探査ケプラー宇宙望遠鏡ミッション詳細 https://japanese.engadget.com/2018/03/15/9-4500/

(Others ) 

Anything you want! Pick something small in [Kaggle.com](http://kaggle.com/) or Google Data Set Serach

**Comment by daijapan** [comment]
@RizwanJdr  cc

**Comment by KosalChansothay** [comment]
This is awesome. I'm grateful for this.

**Comment by daijapan** [comment]
likewise

*Dave Ishii, Mathematician *🔢 石井 大輔 数学者

Founder & CEO, Kiara Inc.

We make the better UX in workplace & finance with AI

**Comment by daijapan** [comment]
Event archive - great people! 

https://x.com/ishiid/status/1746048111926243331?s=20
